config/routes.rb
Rails.application.routes.draw do
  resources :plans
  resources :cash_registers
  resources :calendars
  resources :calendar_days  
  resources :products
  resources :employees
  resources :clients
  resources :sessions
  resources :groups do
    member do
      post 'enroll'
    end
  end

  root to: "home#index"
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :client
  belongs_to :group
  belongs_to :calendar_day

  validate :sufficient_credits

  after_create :deduct_credits

  private

  def sufficient_credits
    if client.credits < 1
      errors.add(:client, "não possui créditos suficientes.")
    end
  end

  def deduct_credits
    client.update(credits: client.credits - 1)
  end
end

app/models/calendar.rb
# app/models/calendar.rb
class Calendar < ApplicationRecord
  has_many :calendar_days, dependent: :destroy
end

app/models/calendar_day.rb
class CalendarDay < ApplicationRecord
  belongs_to :calendar
  has_many :events
  has_many :groups, through: :events

  enum skill_group: {group_1: 1, group_2: 2, group_3: 3, group_4: 4}
  enum training_phase: {phase_1: 1, phase_2: 2, phase_3: 3, phase_4: 4}

  validates :skill_group, inclusion: {in: skill_groups.keys}
  validates :training_phase, inclusion: {in: training_phases.keys}
end

app/models/cash_register.rb
class CashRegister < ApplicationRecord
  has_many :sales, dependent: :destroy

  def calculate_closing_balance
    self.closing_balance = opening_balance + total_sales - total_expenses
  end
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :attendances
  has_many :enrollments
  has_many :groups, through: :enrollments

  def add_credits(plan)
    self.credits += plan.credits
    save
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :groups, foreign_key: 'professor_titular_id'
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :group
  belongs_to :client
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :calendar_day
  belongs_to :session
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :semanal, optional: true 
  belongs_to :professor_titular, class_name: 'Employee', foreign_key: 'professor_titular_id'
  has_many :enrollments
  has_many :clients, through: :enrollments
  has_many :events
  has_many :calendar_days, through: :events

  def display_name
    "#{modality} - #{day} às #{time}"
  end
end

app/models/physical.rb
class Physical < ApplicationRecord
  belongs_to :session

  validates :group, inclusion: { in: %w[MI TR MS], message: "deve ser MI, TR ou MS" }
  validates :phase, inclusion: { in: %w[1 2 3 4], message: "deve ser 1, 2, 3 ou 4" }
  validates :exercise, presence: true 
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :plans_assignments
  has_many :groups, through: :plans_assignments
  has_many :clients, through: :plans_assignments

  validates :name, :frequency, presence: true
end

app/models/plan_assignment.rb
class PlanAssignment < ApplicationRecord
  belongs_to :plan
  belongs_to :group
  belongs_to :client

  validates :plan_id, :group_id, :client_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :cash_register
end

app/models/semanal.rb
class Semanal < ApplicationRecord
  has_many :turmas
end

app/models/session.rb
class Session < ApplicationRecord
  has_one :physical, dependent: :destroy
  has_one :warm_up, class_name: 'WarmUp', dependent: :destroy
  has_many :events

  accepts_nested_attributes_for :physical
  accepts_nested_attributes_for :warm_up

  validates :date, :content, :objective, :skill, presence: true
  validates_associated :physical, :warm_up
end

app/models/turma.rb
class Turma < ApplicationRecord
  belongs_to :semanal, optional: true 
  belongs_to :professor_titular, class_name: 'Employee', foreign_key: 'professor_titular_id'
  has_many :enrollments
  has_many :clients, through: :enrollments
end

app/models/warm_up.rb
class WarmUp < ApplicationRecord
  belongs_to :session

  validates :joint, :cardio, :skill, presence: true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
    @client = Client.find(params[:id])
  end
    
  # GET /clients/new
  def new
    @client = Client.new
  end
  
  # GET /clients/1/edit
  def edit
  end
  
  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def client_params
    params.require(:client).permit(:name, :birth_date, :plan, group_ids: [])
  end
  
end

app/helpers/calendars_helper.rb
module CalendarsHelper
  def translate_day(day)
    translations = {
      "Sunday" => "Domingo",
      "Monday" => "Segunda-Feira",
      "Tuesday" => "Terça-Feira",
      "Wednesday" => "Quarta-Feira",
      "Thursday" => "Quinta-Feira",
      "Friday" => "Sexta-Feira",
      "Saturday" => "Sábado"
    }
    translations[day] || day
  end
end

app/helpers/group_helper.rb
module GroupHelper
  # Retorna os dias únicos dos groups
  def unique_days(groups)
    groups.map(&:day).uniq
  end

  # Retorna os horários únicos e ordenados dos groups
  def sorted_times(groups)
    groups.pluck(:time).uniq.sort
  end

  # Encontra o group correspondente para um dado horário e dia
  def find_group(groups, time, day)
    groups.find { |t| t.time == time && t.day == day }
  end

  # Formata o conteúdo da célula da tabela
  def format_group_cell(group)
    if group
      link_to "#{group.modality} - #{group.age}", group_path(group)
    else
      # Deixa a célula vazia se não houver turma
      ""
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>
      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.date_field :birth_date %>
  </div>

  <div class="field">
    <%= form.label :plan %>
    <%= form.text_field :plan %>
  </div>

  <div class="field">
    <%= form.label :group_ids, "Turmas" %>
    <%= form.collection_select :group_ids, Group.all, :id, :display_name, {}, { multiple: true } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1> Alunos </h1>

<div>
  <ul>
    <% @clients.each do |client| %>
      <li><%= link_to client.name, client_path(client) %></li>
    <% end %>
  </ul>
</div>

<p><%= link_to "Novo Aluno", new_client_path %></p>

app/views/clients/new.html.erb
<h1>New Aluno</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<h1> <%= @client.name %> </h1>

<p> Nascimento: <%= @client.birth_date %> </p>

<p> Plano: <%= @client.plan %> </p>

<p>Aulas:</p>
<ul>
  <% @client.groups.each do |group| %>
    <li>
      Dia: <%= group.day %>, Hora: <%= group.time %>, Modalidade: <%= group.modality %>, Faixa Etária: <%= group.age %>
      <%= link_to "Detalhes", group %>
    </li>
  <% end %>
</ul>

<%= link_to "Editar Cadastro", edit_client_path(@client), class: "btn btn-primary" %>
<%= button_to "Apagar Cadastro", @client, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>